name: Release

on:
  # Run `npm run bump` to bump the version and create a git tag.
  push:
    tags:
      - 'v*'

  workflow_dispatch:

permissions:
  contents: read
  id-token: write # Required for OIDC

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24.18.0
          package-manager-cache: false

      - name: Install Pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: true

      - name: Build Packages
        run: pnpm build

      - name: Publish
        run: pnpm stage publish --no-git-checks
